version: "3"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./data/db_api:/data/db_api"

#  python-api-mongodb:
#    build: "./db_api"
#    container_name: "python-api-mongodb"
#    restart: always
#    ports:
#      - "8001:8000"
#    depends_on:
#      - mongodb