name: Push to any branch
on:
  push:
    branches-ignore:
      - dev
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Exctract branch name
        run: echo "Branch name is ${GITHUB_REF#refs/heads/}"

# TODO: установить docker и docker-compose
# TODO: сборка контейнеров для каждого сервиса
# TODO: прогон тестов для каждого сервиса
