name: CI
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: push
jobs:
  testing:
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python my_script.py


# TODO: установить docker и docker-compose
# TODO: сборка контейнеров для каждого сервиса
# TODO: прогон тестов для каждого сервиса
